name: Build cpyvpn
on:
  push:
    paths:
      - .github/workflows/build-latest.yml
      - Containerfile
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: Build and push to registry
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu dependency
        uses: docker/setup-qemu-action@v3

      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Environment Vars setup
        run: |
          echo "cpyvpn_version=$(git ls-remote --quiet --refs --tags https://gitlab.com/cpvpn/cpyvpn.git | cut --delimiter='/' --fields=3 | grep -Eo '^[[:digit:]]+.[[:digit:]]+.[[:digit:]]+$' | sort --version-sort | tail -n1)" >> "$GITHUB_ENV"

      - name: Tar as root
        run: |
          sudo mv -fv /usr/bin/tar /usr/bin/tar.orig
          echo -e '#!/bin/sh\n\nsudo /usr/bin/tar.orig "$@"' | sudo tee -a /usr/bin/tar
          sudo chmod +x /usr/bin/tar

      - name: Enable caching for podman
        id: cache-podman
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/containers
          key: ${{ runner.os }}-${{ runner.arch }}-cpyvpn-latest

      - name: Podman Socket
        run: |
          podman system service  --time=0 unix:///tmp/podman.sock &
          mkdir -pv /run/user/1001/podman/
          ln -sv /tmp/podman.sock /run/user/1001/podman/podman.sock

      - name: Fetch trivy
        run: |
          podman pull docker.io/aquasec/trivy:latest

      - name: Log in to Quay
        uses: redhat-actions/podman-login@v1
        with:
          registry: "quay.io"
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build containers
        id: build-dev
        uses: redhat-actions/buildah-build@v2
        with:
          image: cpyvpn
          tags: latest stable ${{ env.cpyvpn_version }}
          layers: true
          platforms: linux/amd64, linux/arm/v5, linux/arm/v7, linux/arm64/v8
          containerfiles: |
            ./Containerfile
          build-args: |
            BRANCH=${{ env.cpyvpn_version }}

      - name: Push to Quay - origin branch latest release 
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-dev.outputs.image }}
          tags: ${{ steps.build-dev.outputs.tags }}
          registry: quay.io/pqatsi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: '${{ steps.build-dev.outputs.image }}'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: cpyvpn-latest.sarif
          limit-severities-for-sarif: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'cpyvpn-latest.sarif'
